"""detalle de pago con bold

Revision ID: bcb4f8e92edc
Revises: c4f8a1b2d3e4
Create Date: 2026-08-04 16:06:23.629142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bcb4f8e92edc'
down_revision: Union[str, Sequence[str], None] = 'c4f8a1b2d3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymentdetail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('identity_key_bold', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('secret_key_bold', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color_button', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size_button', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('redirect_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paymentdetail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paymentdetail_store_id'), ['store_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paymentdetail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paymentdetail_store_id'))

    op.drop_table('paymentdetail')
    # ### end Alembic commands ###
